config/routes.rb
Rails.application.routes.draw do

  resources :accounts
  resources :bills do
    member do
      patch :pay
    end
  end

  root "bills#index"

end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord

  def account_name
    Account.find(account_id).name
  end

  def paid?
    paid_date.present? && paid_amount == due_amount
  end

  def due_amount
    (self[:due_amount].to_f / 100.0).round(2)
  end

  def paid_amount
    (self[:paid_amount].to_f / 100.0).round(2)
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy, :pay]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    new_bill_params = bill_params
    new_bill_params[:due_amount] = bill_params[:due_amount].to_f * 100

    new_bill_params[:paid_date] = nil

    @bill = Bill.new(new_bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to "/", notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    update_bill_params = bill_params
    
    puts "=====> BEFORE #{update_bill_params[:due_amount]}"
    update_bill_params[:due_amount] = bill_params[:due_amount].to_f * 100
    puts "=====> AFTER #{update_bill_params[:due_amount]}"

    update_bill_params[:paid_amount] = bill_params[:paid_amount].to_f * 100

    respond_to do |format|
      if @bill.update(update_bill_params)
        format.html { redirect_to "/", notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pay
    @bill.update({ paid_date: Time.now, paid_amount: @bill[:due_amount] })
    redirect_to bills_url, notice: 'Bill was successfully paid'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:name, :notes, :due_amount, :due_date, :paid_date, :paid_amount, :recurring, :automatic, :account_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :account_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :account_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="title">
  <h1>Accounts</h1>
  <%= link_to new_account_path do %>
    <%= fa_icon "plus-circle", class: "fa-3x" %>
  <% end %>
</div>

<% @accounts.order(:name).each do |account| %>
  <div class="card">
    <div class="card-title">
      <h2><%= account.name %></h2>
      <div class="card-actions">
        <%= link_to edit_account_path(account) do %>
          <%= fa_icon "pencil" %>
        <% end %>
        <%= link_to account, method: :delete, data: { confirm: "Are you sure?" } do %>
          <%= fa_icon "trash" %>
        <% end %>
      </div>
    </div>
    <div>
      <a href="<%= account.url %>" target="_blank">Visit <%= fa_icon "external-link" %></a>
    </div>
  </div>
<% end %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @account.url %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/bills/_form.html.erb
<%= form_with(model: bill, local: true) do |form| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :bill_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :bill_url %>
  </div>

  <div class="field">
    <%= form.label :due_amount %>
    <%= form.number_field :due_amount, step: :any, id: :bill_due_amount %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date, id: :bill_due_date %>
  </div>

  <div class="field">
    <%= form.label :recurring %>
    <%= form.check_box :recurring, id: :bill_recurring %>
  </div>

  <div class="field">
    <%= form.label :automatic %>
    <%= form.check_box :automatic, id: :bill_automatic %>
  </div>

  <div class="field">
    <%= form.label :paid_amount %>
    <%= form.number_field :paid_amount, id: :bill_paid_amount %>
  </div>

  <div class="field">
    <%= form.label :paid_date %>
    <%= form.date_select :paid_date, id: :bill_paid_date %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :bill_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form', bill: @bill %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<div class="title">
  <h1>Bills</h1>
  <%= link_to new_bill_path do %>
    <%= fa_icon "plus-circle", class: "fa-3x" %>
  <% end %>
</div>

<% @bills.order(:due_date).each do |bill| %>
  <%= link_to bill do %>
    <div class="card">
      <div class="card-title">
        <h2><%= bill.account_name %></h2>
        <% if bill.paid? %>
          <%= fa_icon "check", class: "fa-2x fc-g" %>
        <% end %>
      </div>
      <div>
        <span class="due">$<%= '%.2f' % bill.due_amount %></span>
        <% if bill.paid? %>
          paid on the <%= bill.paid_date.day.ordinalize %>
        <% else %>
          due on the <%= bill.due_date.day.ordinalize %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= form_with(model: @bill, local: true) do |form| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :bill_name %>
  </div>

  <div class="field">
    <%= form.label :account %>
    <%= form.collection_select :account_id, Account.order(:name), :id, :name %>
  </div>

  <div class="field">
    <%= form.label :due_amount %>
    <%= form.number_field :due_amount, step: :any, id: :bill_due_amount %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date, id: :bill_due_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @bill.name %>
  $<%= '%.2f' % @bill.due_amount %>
</h1>

<p>
  <strong>Due date:</strong>
  <%= @bill.due_date.strftime("%m/%d") %>
</p>

<p>
  <strong>Paid date:</strong>
  <% if @bill.paid? %>
    <%= @bill.paid_date.strftime("%m/%d") %>
  <% else %>
    &mdash;
  <% end %>
</p>

<p>
  <strong>Paid amount:</strong>
  $<%= '%.2f' % @bill.paid_amount %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @bill.notes %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/layouts/_nav.html.erb
<nav>
  <%= link_to "Bills", "/bills" %>
  <%= link_to "Accounts", "/accounts" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bills</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/nav"%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>